// config.h
#pragma once

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK


#define RGBLIGHT_ANIMATIONS
// #undef RGBLIGHT_ANIMATIONS
// #define RGBLIGHT_EFFECT_STATIC_GRADIENT
// #define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

#define RGBLIGHT_DEFAULT_SPD 2
